### PR TITLE
use GunicornPrometheusMetrics

### PR DESCRIPTION
**Pull request by charlienegri**
**Summary**: use GunicornPrometheusMetrics

**Related issue**: #220

**Suggested reviewer(s)**:

**Reviewer checklist**:

* [ ] The headers of all files contain a reference to the repository license
* [ ] 100% test coverage of new code - meaning:
  * [ ] The overall test coverage increased or remained the same as before
  * [ ] Every function is accompanied with a test suite
  * [ ] Tests are both positive (testing that the function work as intended with valid data) and negative (testing that the function behaves as expected with invalid data, e.g., that correct exceptions are thrown)
  * [ ] Functions with optional arguments have separate tests for all options
* [ ] Examples are supported by doctests
* [ ] All tests are passing
* [ ] All names (e.g., files, classes, functions, variables) are explicit
* [ ] Documentation (as docstrings) is complete and understandable

The checklist is based on the S-ENDA conventions and definition of done (see [General Conventions](https://s-enda-documentation.readthedocs.io/en/latest/general_conventions.html)). The above points are not necessarily relevant to all contributions. In that case, please add a short explanation to help the reviewer.

### CODE REVIEW

**Comment by charlienegri** [comment]
@magnarem this exposes the /metrics endpoint correctly at port 9200 (could not use 8000) when run in a container locally but I am not 100% sure if it accounts correctly for the different workers
Screenshot from 2024-10-03 18-57-42

**Comment by magnarem** [comment]
I added some comment to issue #220. 

Reviewed and accepted and merged this.

**Review by magnarem — APPROVED** [review]
reviewed and approved

**Comment by charlienegri** [comment]
we might need an extra 
EXPOSE 9200 
in the Dockerfile

**Pull request merged**
