### PR TITLE
add prometheus_flask_exporter

### PR DESCRIPTION
**Pull request by charlienegri**
**Summary**: extract metrics via prometheus_flask_exporter

**Related issue**:
#220

**Suggested reviewer(s)**:

**Reviewer checklist**:

* [ ] The headers of all files contain a reference to the repository license
* [ ] 100% test coverage of new code - meaning:
  * [ ] The overall test coverage increased or remained the same as before
  * [ ] Every function is accompanied with a test suite
  * [ ] Tests are both positive (testing that the function work as intended with valid data) and negative (testing that the function behaves as expected with invalid data, e.g., that correct exceptions are thrown)
  * [ ] Functions with optional arguments have separate tests for all options
* [ ] Examples are supported by doctests
* [ ] All tests are passing
* [ ] All names (e.g., files, classes, functions, variables) are explicit
* [ ] Documentation (as docstrings) is complete and understandable

The checklist is based on the S-ENDA conventions and definition of done (see [General Conventions](https://s-enda-documentation.readthedocs.io/en/latest/general_conventions.html)). The above points are not necessarily relevant to all contributions. In that case, please add a short explanation to help the reviewer.

### CODE REVIEW

**Comment by charlienegri** [comment]
Screenshot from 2024-10-01 15-04-28
local test seem to expose the metrics at least

**Comment by charlienegri** [comment]
@magnarem this should not conflict with the catalog-rebuilder-flask metrics endpoint right? because dmci has its own container port (8000)

**Comment by magnarem** [comment]
I think it should be no problem. The k8s nginx in front of dmci, should handle request dmci.s-enda.k8s.met.no/metrics og catalog-rebuilder.s-enda.k8s.met.no/metrics to the right ones...If unsure, maybe the k8s people can give a better answer.

**Comment by charlienegri** [comment]
Screenshot from 2024-10-02 11-49-19

**Review by magnarem — COMMENTED** [review]
Looks good. Let's see if it works.

**Review by magnarem — APPROVED** [review]
Let's see if it works in dev

**Comment by charlienegri** [comment]
I think we'll need to add annotations to the `base/dmci/statefulset.yaml` in the tjeneste repo for the metrics to be actually scraped, as there are for `catalog-rebuilder-flask`, basically identical lines but just with a changed port, should be 8000 if I read the code right

**Comment by charlienegri** [comment]
🙃 I added it to the requirements file and forgot about that ... I will open a PR to fix this

**Comment by charlienegri** [comment]
patch https://github.com/metno/discovery-metadata-catalog-ingestor/pull/234

**Pull request merged**
