### PR TITLE
back to GunicornPrometheusMetrics, CollectorRegistry, port 9200

### PR DESCRIPTION
**Pull request by charlienegri**
**Summary**: this again for me exposes all the metrics at port 9200 when I run the container with docker....

**Related issue**: #220 

**Suggested reviewer(s)**:

**Reviewer checklist**:

* [ ] The headers of all files contain a reference to the repository license
* [ ] 100% test coverage of new code - meaning:
  * [ ] The overall test coverage increased or remained the same as before
  * [ ] Every function is accompanied with a test suite
  * [ ] Tests are both positive (testing that the function work as intended with valid data) and negative (testing that the function behaves as expected with invalid data, e.g., that correct exceptions are thrown)
  * [ ] Functions with optional arguments have separate tests for all options
* [ ] Examples are supported by doctests
* [ ] All tests are passing
* [ ] All names (e.g., files, classes, functions, variables) are explicit
* [ ] Documentation (as docstrings) is complete and understandable

The checklist is based on the S-ENDA conventions and definition of done (see [General Conventions](https://s-enda-documentation.readthedocs.io/en/latest/general_conventions.html)). The above points are not necessarily relevant to all contributions. In that case, please add a short explanation to help the reviewer.

### CODE REVIEW

**Comment by charlienegri** [comment]
Screenshot from 2024-10-08 11-55-33
@magnarem I am out of ideas, this works for me locally, again

**Review by magnarem — APPROVED** [review]
Approved. And merged. Le'ts hope this works now.

If not, I bet the issue is related to the `wsgi.py` file. Since the gunicorn process loads `wsgi:app`then in the `wsgi.py` file, I am not sure if the lines after `app = App()` is then loaded by gunicorn.

Also in the `statefulset.yml` for dmci in the tjenester-repo. The gunicorn command from the Dockerfile is overrided, so you will probably need to add the `-c /src/gunicorn_prometheus_config.py` to the `command:` for the dmci container in the `statefulset.yml` too. And make sure the 9200 is exposded and scraped

**Comment by charlienegri** [comment]
> Approved. And merged. Le'ts hope this works now.
> 
> If not, I bet the issue is related to the `wsgi.py` file. Since the gunicorn process loads `wsgi:app`then in the `wsgi.py` file, I am not sure if the lines after `app = App()` is then loaded by gunicorn.
> 
> Also in the `statefulset.yml` for dmci in the tjenester-repo. The gunicorn command from the Dockerfile is overrided, so you will probably need to add the `-c /src/gunicorn_prometheus_config.py` to the `command:` for the dmci container in the `statefulset.yml` too. And make sure the 9200 is exposded and scraped

we got the flask metrics exposed correctly at the 9200 port tho initially, before I implemente the custom ones, so I think that the GunicornPrometheusMetrics() or variants of it in wsgi.py works, but the problem is having both those default ones and the custom one exposed at the same port and by the same collector

**Comment by charlienegri** [comment]
mmh `/src/gunicorn_prometheus_config.py' doesn't exist`

**Comment by magnarem** [comment]
Also for the 9200 Port, you will probably have to add a special ingress in the ingress.yml in the dmci base folder.

```
 rules:
    - host: "dmci.s-enda.k8s.met.no"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dmci
                port:
                  name: http
        - path:/flask-metrics
         pathType: Prefix?
         backend:
         service:
           name: dmci
           port:
             name: http-flask-metrics
             ```
             
             and then in statefulset
             
             ```
               ports:
            - name: http
              containerPort: 8000
              protocol: TCP
         - name: http-flask-metrics
           port: 9200
           protocol: TCP
           ``

**Comment by charlienegri** [comment]
the exposure of 9200 in the statefulset is already there, I had added it, removed it and added it back after last update  
the endpoint seems also to have everything now https://dmci.s-enda-dev.k8s.met.no/metrics

**Comment by charlienegri** [comment]
> yeah. you probably not need this copy statement. Since the `gunicorn_prometheus_config.py` resides in container/ folder together with the `wsgi.py` both files are copied to root, so you will not need this line `COPY container/gunicorn_prometheus_config.py /src`
> 
> and then the gunicorn command should work with:
> 
> `CMD gunicorn -c gunicorn_prometheus_config.py --worker-class sync --workers 5 --bind 0.0.0.0:8000 wsgi:app --keep-alive 5 --log-level info`
> 
> Also I see no problem with our custom metrics (the failed dist) you implemented is exposed on different port than the other prometheus flask metrics. You can have multiple annotations for scraping in kubernetes I imagine.

gunicorn_prometheus_config.py is indeed in the root folder of the container so as you say we can skip the copy to src step

**Comment by charlienegri** [comment]
while looking at the federated metrics I see some inconsistencies.. I fear the exposure might happen on one instance only :/

**Pull request merged**
