### PR TITLE
Issue27 validation

### PR DESCRIPTION
**Pull request by mortenwh**
**Summary**: This is just the old tests for check_mmd.py. It has been removed from py-mmd-tools and we may want to use it to have coverage for check_mmd.py as well.

**Related issue**: #27 (which has already been closed)

**Suggested reviewer(s)**: @vkbo 

**Reviewer checklist**:

* [ ] The headers of all files contain a reference to the repository license
* [ ] 100% test coverage of new code - meaning:
  * [ ] The overall test coverage increased or remained the same as before
  * [ ] Every function is accompanied with a test suite
  * [ ] Tests are both positive (testing that the function work as intended with valid data) and negative (testing that the function behaves as expected with invalid data, e.g., that correct exceptions are thrown)
  * [ ] Functions with optional arguments have separate tests for all options
* [ ] Examples are supported by doctests
* [ ] All tests are passing
* [ ] All names (e.g., files, classes, functions, variables) are explicit
* [ ] Documentation (as docstrings) is complete and understandable

The checklist is based on the S-ENDA conventions and definition of done (see [General Conventions](https://s-enda-documentation.readthedocs.io/en/latest/general_conventions.html)). The above points are not necessarily relevant to all contributions. In that case, please add a short explanation to help the reviewer.

### CODE REVIEW

**Comment by vkbo** [comment]
This PR has a completely different test setup than the rest of the code.

**Comment by vkbo** [comment]
Also, coverage is not 100%, so tests need updating anyway.

**Comment by vkbo** [comment]
I've moved the tests over to the pytest module. Even though pytest could run the unittest based tests, making them proper pytests means that the pytest features work properly, like the filtering commands. In addition, having tests in different places makes it harder to maintain the test suite as the unittests were inside the source.

In the process, I also made sure the tests for the rectangle checker trigger the actual errors they are supposed to. There was a bug in the function itself that would determine a coordinate at long or lat 0.0 as invalid. This has now been fixed. This brought test coverage to 100%.

I also deleted the two XML files added as they were not used by any of the tests.

**Review by johtoblan — APPROVED** [review]
LGTM

**Pull request merged**
